### ISSUE TITLE
Changing toaster settings replaces settings instead of extending

### ISSUE THREAD

**Issue by scottoffen** [scottoffen/jquery.toaster#1]
Attempting to change the CSS in the toaster settings replaced the toaster settings object instead of extending it.

Example:
$.toaster({ settings : {  toaster : { css : { "bottom" : "0px" } } } });

**Comment by scottoffen** [comment]
I think I'll fix this by moving the settings to a separate method call:

$.toaster.settings('toaster', { css : { "bottom" : "0px" } } );

or maybe

$.toaster.settings.toaster('css', { "bottom" : "0px" });

**Comment by jairmilanes** [comment]
I had the same problem, the solution I've found was this:

```
 settings = $.extend(true, {}, settings, options.settings);
```

This will recursively re-build the settings object correctly, hope it helps!
