### ISSUE TITLE
Support this as a bower package

### ISSUE THREAD

**Issue by gtaborga** [scottoffen/jquery.toaster#3]
Hey Scott,

I'm not sure if you're still supporting this project or not. Any chance it can be made a bower package?

Best regards,

Gunther

**Comment by scottoffen** [comment]
Yes, this is still being supported. I'll be adding support for npm, too.

**Comment by jpchip** [comment]
Looking forward to this being available on npm or bower!

**Comment by dreamcasting** [comment]
Agreed - just am getting on the Bower/NPM bandwagon and love the idea of more automatic-style management. Looking forward to it being enhanced!

**Comment by scottoffen** [comment]
Decided on bower for now, no npm unless there is a strong desire to have it.
